### ISSUE TITLE
Concentrated or distributed?

### ISSUE THREAD

**Issue by mesutto** [mesutto/IMMD#3]

**Comment by ozank** [comment]
valla slot sayısı az olacaksa, concentrated sardırmak daha kolay olacaktır. Concentrated bence modüler yapı için de daha mantıklı, ayrıca tork density genelde daha yüksek ama harmonik sıkıntılarına dikkat etmek lazım.

Slot sayısı çoksa ve her slottan ayrı bir bağlantı istemiyorsak, distributed yapmak durumunda kalırız.
