### ISSUE TITLE
GaN Modellenmesi Yol Haritası 

### ISSUE THREAD

**Issue by furkankarakaya** [mesutto/IMMD#5]
Merhaba, modelleme adımları ve seçenekleri ile ilgili bir dosya yükledim. Müsait bir vaktinizde feedback verebilir misiniz? 
https://github.com/mesutto/IMMD/blob/master/Project/3501/Furkan/GaN%20Modelleme%20stepler.pdf
@ozank @mesutto @MelisaSarici

**Comment by ozank** [comment]
En son konuştuğumuzda Seçenek-2 öne çıkıyor demiştin. Onu mu kullanmaya karar verdiniz? Salı günü tartışalım en kötü
