### ISSUE TITLE
Capacitance modelleme hakkında

### ISSUE THREAD

**Issue by MelisaSarici** [mesutto/IMMD#6]
@furkankarakaya 
Capacitance modellemedeki parametreler için referans aldığın kaynak hangisi Furkan?

**Comment by furkankarakaya** [comment]
Aslında tam bir kaynak kullanmıyorum. Datasheet'ten dataları çıkarıp onları MATLAB'da fit ettim. Sonra da variable capacitor'a hesaplayıp input olarak verdim.
